language: python
dist: trusty
sudo: false

cache:
  pip: true
  directories:
    - $HOME/.ccache

env:
  global:
    - USE_CCACHE=1
    - CCACHE_SLOPPINESS=pch_defines,time_macros
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=70M
    - PATH="/usr/lib/ccache:$PATH"
    - LIBXSLT_VERSION=1.1.32

matrix:
  include:
    - python: 2.7
      env: STATIC_DEPS=true
    - python: 2.7
      env: STATIC_DEPS=false
    - python: 3.6
      env: STATIC_DEPS=true
    - python: 3.6
      env: STATIC_DEPS=false
    - python: 3.5
      env: STATIC_DEPS=true
    - python: 3.5
      env: STATIC_DEPS=false
    - python: 3.4
      env: STATIC_DEPS=true
    - python: 3.4
      env: STATIC_DEPS=false
    - python: 3.3
      env: STATIC_DEPS=true
    - python: 3.3
      env: STATIC_DEPS=false
    - python: 3.7
      dist: xenial  # Required for Python 3.7
      sudo: true    # travis-ci/travis-ci#9069
      env: STATIC_DEPS=true
    - python: 3.7
      dist: xenial  # Required for Python 3.7
      sudo: true    # travis-ci/travis-ci#9069
      env: STATIC_DEPS=false
    - python: 3.8-dev
      dist: xenial  # Required for Python 3.7+
      sudo: true    # travis-ci/travis-ci#9069
      env: STATIC_DEPS=true
    - python: 3.8-dev
      dist: xenial  # Required for Python 3.7+
      sudo: true    # travis-ci/travis-ci#9069
      env: STATIC_DEPS=false
    - python: pypy
      env: STATIC_DEPS=false
    - python: pypy3
      env: STATIC_DEPS=false

install:
    - pip install -U pip wheel
    - pip install $(if [ -z "${TRAVIS_PYTHON_VERSION##*-dev}" ]; then echo "--install-option=--no-cython-compile"; fi ) -r requirements.txt
    - pip install -U beautifulsoup4 cssselect html5lib

before_script: ccache -s || true

script:
  - CFLAGS="-O0 -g -fPIC" python -u setup.py build_ext --inplace $(if [ -n "${TRAVIS_PYTHON_VERSION##2.*}" -a -n "${TRAVIS_PYTHON_VERSION##3.[34]*}" ]; then echo -n " -j7 "; fi )
  - CFLAGS="-O0 -g -fPIC" PYTHONUNBUFFERED=x make test

matrix:
  allow_failures:
    - python: 3.8-dev
    - python: pypy
    - python: pypy3
